# Kubernetes Resources Configuration

**Feature**: 013-phasev-infra-deployment
**Date**: 2026-02-14
**Version**: 1.0.0

## Overview

This document defines Kubernetes resource configurations for all services in both local (Minikube) and cloud (Oracle Cloud) environments.

---

## Namespace

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: todo-app
  labels:
    name: todo-app
    environment: production
```

---

## Deployments

### Frontend Deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: todo-app
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/your-org/todo-frontend:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://backend.todo-app.svc.cluster.local:8000"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
```

### Backend Deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: todo-app
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "backend"
        dapr.io/app-port: "8000"
        dapr.io/app-protocol: "http"
        dapr.io/config: "dapr-config"
        dapr.io/log-level: "info"
        dapr.io/enable-metrics: "true"
        dapr.io/metrics-port: "9090"
        dapr.io/sidecar-cpu-limit: "200m"
        dapr.io/sidecar-memory-limit: "256Mi"
        dapr.io/sidecar-cpu-request: "100m"
        dapr.io/sidecar-memory-request: "128Mi"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: backend
        image: ghcr.io/your-org/todo-backend:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: neon-secret
              key: connectionString
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        - name: DAPR_HTTP_PORT
          value: "3500"
        - name: DAPR_GRPC_PORT
          value: "50001"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 300m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
```

### Event Processor Deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-processor
  namespace: todo-app
  labels:
    app: event-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-processor
  template:
    metadata:
      labels:
        app: event-processor
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "event-processor"
        dapr.io/app-port: "8001"
        dapr.io/app-protocol: "http"
        dapr.io/config: "dapr-config"
        dapr.io/log-level: "info"
        dapr.io/enable-metrics: "true"
        dapr.io/metrics-port: "9090"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: event-processor
        image: ghcr.io/your-org/todo-event-processor:latest
        ports:
        - containerPort: 8001
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: neon-secret
              key: connectionString
        - name: DAPR_HTTP_PORT
          value: "3500"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
```

### Reminder Scheduler Deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reminder-scheduler
  namespace: todo-app
  labels:
    app: reminder-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reminder-scheduler
  template:
    metadata:
      labels:
        app: reminder-scheduler
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "reminder-scheduler"
        dapr.io/app-port: "8002"
        dapr.io/app-protocol: "http"
        dapr.io/config: "dapr-config"
        dapr.io/log-level: "info"
        dapr.io/enable-metrics: "true"
        dapr.io/metrics-port: "9090"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8002"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: reminder-scheduler
        image: ghcr.io/your-org/todo-reminder-scheduler:latest
        ports:
        - containerPort: 8002
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: neon-secret
              key: connectionString
        - name: DAPR_HTTP_PORT
          value: "3500"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 10
          periodSeconds: 5
```

### Notification Service Deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: todo-app
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "notification-service"
        dapr.io/app-port: "8003"
        dapr.io/app-protocol: "http"
        dapr.io/config: "dapr-config"
        dapr.io/log-level: "info"
        dapr.io/enable-metrics: "true"
        dapr.io/metrics-port: "9090"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8003"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: notification-service
        image: ghcr.io/your-org/todo-notification-service:latest
        ports:
        - containerPort: 8003
          name: http
        env:
        - name: DAPR_HTTP_PORT
          value: "3500"
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 10
          periodSeconds: 5
```

### WebSocket Service Deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service
  namespace: todo-app
  labels:
    app: websocket-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: websocket-service
  template:
    metadata:
      labels:
        app: websocket-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "websocket-service"
        dapr.io/app-port: "8004"
        dapr.io/app-protocol: "http"
        dapr.io/config: "dapr-config"
        dapr.io/log-level: "info"
        dapr.io/enable-metrics: "true"
        dapr.io/metrics-port: "9090"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8004"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: websocket-service
        image: ghcr.io/your-org/todo-websocket-service:latest
        ports:
        - containerPort: 8004
          name: http
        env:
        - name: DAPR_HTTP_PORT
          value: "3500"
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 10
          periodSeconds: 5
```

---

## Services

### Frontend Service

```yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: todo-app
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: frontend
```

### Backend Service

```yaml
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: todo-app
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: backend
```

### Event Processor Service

```yaml
apiVersion: v1
kind: Service
metadata:
  name: event-processor
  namespace: todo-app
  labels:
    app: event-processor
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: event-processor
```

### Reminder Scheduler Service

```yaml
apiVersion: v1
kind: Service
metadata:
  name: reminder-scheduler
  namespace: todo-app
  labels:
    app: reminder-scheduler
spec:
  type: ClusterIP
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: http
  selector:
    app: reminder-scheduler
```

### Notification Service

```yaml
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: todo-app
  labels:
    app: notification-service
spec:
  type: ClusterIP
  ports:
  - port: 8003
    targetPort: 8003
    protocol: TCP
    name: http
  selector:
    app: notification-service
```

### WebSocket Service

```yaml
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  namespace: todo-app
  labels:
    app: websocket-service
spec:
  type: ClusterIP
  ports:
  - port: 8004
    targetPort: 8004
    protocol: TCP
    name: http
  selector:
    app: websocket-service
```

---

## Ingress

### Local Ingress (Minikube - Traefik)

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-app-ingress
  namespace: todo-app
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: todo-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: websocket-service
            port:
              number: 8004
```

### Cloud Ingress (Oracle Cloud - Traefik with TLS)

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-app-ingress
  namespace: todo-app
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - todo-app.example.com
    secretName: todo-app-tls
  rules:
  - host: todo-app.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: websocket-service
            port:
              number: 8004
```

---

## ConfigMaps

### Application Configuration

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: todo-app
data:
  LOG_LEVEL: "info"
  ENVIRONMENT: "production"
  KAFKA_TOPICS: "task-events,reminders,task-updates"
  EVENT_RETENTION_DAYS: "7"
  REMINDER_CHECK_INTERVAL: "60"
```

---

## HorizontalPodAutoscaler

### Backend HPA

```yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: todo-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
```

### Event Processor HPA

```yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: event-processor-hpa
  namespace: todo-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: event-processor
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
```

---

## ResourceQuota (Oracle Cloud Always Free)

```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: todo-app
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "12Gi"
    limits.cpu: "3"
    limits.memory: "14Gi"
    pods: "20"
```

---

## NetworkPolicy

### Backend Network Policy

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-netpol
  namespace: todo-app
spec:
  podSelector:
    matchLabels:
      app: backend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontend
    - podSelector:
        matchLabels:
          app: ingress-controller
    ports:
    - protocol: TCP
      port: 8000
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: event-processor
    ports:
    - protocol: TCP
      port: 8001
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 5432  # PostgreSQL
    - protocol: TCP
      port: 9092  # Kafka
```

---

## PodDisruptionBudget

### Backend PDB

```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: todo-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: backend
```

### Event Processor PDB

```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: event-processor-pdb
  namespace: todo-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: event-processor
```

---

## ServiceAccount

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: todo-app-sa
  namespace: todo-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: todo-app-role
  namespace: todo-app
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: todo-app-rolebinding
  namespace: todo-app
subjects:
- kind: ServiceAccount
  name: todo-app-sa
  namespace: todo-app
roleRef:
  kind: Role
  name: todo-app-role
  apiGroup: rbac.authorization.k8s.io
```

---

## Summary

This configuration provides:
- ✅ Complete Kubernetes deployments for all 6 services
- ✅ ClusterIP services for internal communication
- ✅ Ingress configurations for local (HTTP) and cloud (HTTPS)
- ✅ HorizontalPodAutoscaler for backend and event processor
- ✅ ResourceQuota for Oracle Cloud Always Free tier compliance
- ✅ NetworkPolicy for security
- ✅ PodDisruptionBudget for high availability
- ✅ ServiceAccount and RBAC for secure access

**Resource Allocation Summary**:
- Frontend: 2 replicas × (100m CPU, 256Mi RAM) = 200m CPU, 512Mi RAM
- Backend: 2 replicas × (200m CPU, 512Mi RAM) = 400m CPU, 1Gi RAM
- Event Processor: 2 replicas × (100m CPU, 256Mi RAM) = 200m CPU, 512Mi RAM
- Reminder Scheduler: 1 replica × (100m CPU, 256Mi RAM) = 100m CPU, 256Mi RAM
- Notification Service: 1 replica × (50m CPU, 128Mi RAM) = 50m CPU, 128Mi RAM
- WebSocket Service: 2 replicas × (50m CPU, 128Mi RAM) = 100m CPU, 256Mi RAM
- Dapr Sidecars: 10 sidecars × (100m CPU, 128Mi RAM) = 1000m CPU, 1.28Gi RAM
- **Total Requests**: 2.05 CPU, 3.9Gi RAM (within 2 OCPU, 12GB limit with overcommit)

**Status**: Kubernetes resources configuration complete
