apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
  namespace: default
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []
scopes:
- todo-api
- recurring-task-service
- notification-service
---
# Local development secrets component (file-based)
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-secrets
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: "./secrets.json"
  - name: nestedSeparator
    value: ":"
scopes:
- todo-api
---
# Production Kubernetes secrets configuration
# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: kubernetes-secrets
#   namespace: production
# spec:
#   type: secretstores.kubernetes
#   version: v1
#   metadata: []
# scopes:
# - todo-api
# - recurring-task-service
# - notification-service
#
# Usage example:
# secrets = await dapr_client.get_secret(
#     store_name="kubernetes-secrets",
#     key="database-connection-string"
# )
